# Python Review

Short reivew about some core concepts in Python exemplified by obhects in the Numpy Library. 

Goals: 
-recall basic python vocab
-practice markdown syntax

## Libraries and Packages
a library is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files. 

**NumPy:**
- core library for numerical computing in Python
- many of libraries use Numpy arrays as theur building blocks
- computations on Numpy objects are optimized for speed and memory usage. 

Let's import NumPy with its **standard abbreviation** np:

In [1]:
import numpy as np

## Variables 
**variable:** a name we assign to a particular object in Python
-- Example:

In [2]:
# Assign a small array to variable a
a = np.array([[1,1,2],[3,5,8]])

In [3]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: Use `snake_case` for naming variables.

This is the convention we will use in this course. 

**Remember that varialbe names should be both descriptive and concise!**

## Objects

**object:** is a bundle of properties and actions about something specific. 

Exmaple:

Object: data frame
Properties: number of rows, names of columns, and date created
Actions: selecting a specific row or adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables. 

In practice, we can often use the word variable and object interchangeably. 

## Types  

Every object in Python has a type. The type tells us what kind of object we have. 
We can also call the tyoe of an object the **class** of an object. Class and Object both mean what kind of object we have. 


In [5]:
print(a)

[[1 1 2]
 [3 5 8]]


In [6]:
type(a)

numpy.ndarray

The `numpy.ndarray` is the core object/ data type of the NumPy package. 

In [7]:
type(a[0,0])

numpy.int64

The `numpy.int64` is not the standard Python integer type `int`.
`numpy.int64` is a special data type in Numpy telling us that 1 is an integer stored as a 64-bit number. 

Check-in: access the value 5 in array `a`.

In [10]:
print(a[1,1])

5


## Functions

`print` was our first example of a python function. 
Functions take in a set of arguments, separated by commas, adnt hey use those arguments to create an output. 
In this course we will be using argument and parameter interchangeably. But, they do have slightly different meanings. 
We can ask for info about what a function does by executing ? followed by the function name.

In [11]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we get is a **docstring**, a special type of comment that is used to document how a function (or a class or module) works. 

Notice that there are different types of arguments inside the function parenthesis. 

Roughly speaking, a function has two types of arguments:

- **non optional arguments**: arguments you have to specify for the function to work.
- **optional arguments:** arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis in the form `optional_argument = default_value`.

Example:

`end` is a parameter in `print` with default value a new line. 
We can pass the value `:)` to this parameter so that it finishes the line with `:)` instead:

In [17]:
print('change the end parameter', end=" :)")

change the end parameter :)

## Attributes and Methods

an Object in Python has attributes and methods. 

- attributes: a property of the object, some piece of info from it.
- method: a procedure associated with an object, so it is an action where the main ingredient is the object itself. 

## Check In:

Make a diagram like the cat one for a class called `fish`. 
We made a diagram lol.


Numpy Arrays have many methods and attributes. For example:

In [18]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [19]:
# T is an exmaple of an attribute, it returns the transpose of an array:
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [20]:
type(a.T)

numpy.ndarray

In [22]:
# shape is another attribute that tells us the shape of the array
print(a.shape)
print(type(a.shape))

(2, 3)
<class 'tuple'>


In [23]:
# ndim is an attribute holding the number of array dimenstions.
print('dim', a.ndim, '| type:', type(a.ndim))

dim 2 | type: <class 'int'>


Attributes can have many different data types. 
Some examples of methods:

In [31]:
# the min method returns the minimum value in the array along a specified axis. 
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

Remember, methods are functions associated with an object. We can confirm this!

In [34]:
# method tolist() transforms array into a list:
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [35]:
type(a.tolist())

list

Exercise:

1. Read the print function help. What is the type of the argument `sep`? Is this a default argument or no? Why?
`sep` is an optional default

2. Create two new variables, one with the integer value 77 and another one with the string 99. 

3. Use your variables to print 77%99%77 by changing the value of one of the default arguments in print.

In [36]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [37]:
a = 77

In [39]:
type(a)

int

In [40]:
b = "99"

In [41]:
b

'99'

In [43]:
type(b)

str

In [48]:
print(a, b, a, sep='%')

77%99%77


1. The integer number -999 is often used to represent missing values. Create a pandas.Series named s with four integer values, two of which are -999. The index of this series should be the the letters A through D.



2. In the pandas.Series documentation, look for the method mask(). Use this method to update the series s so that the -999 values are replaced by NA values. HINT: check the first example in the method’s documentation.


In [62]:
import pandas as pd
s = pd.Series([1, 2, -999, -999], ['A', 'B', 'C', 'D'])

In [63]:
s

A      1
B      2
C   -999
D   -999
dtype: int64

In [67]:
s = s.mask(s<0)
s

A    1.0
B    2.0
C    NaN
D    NaN
dtype: float64

3. We can access the data frame’s column names via the columns attribute. Update the column names to C1 and C2 by updating this attribute.

In [68]:
# Initialize dictionary with columns' data 
d = {'col_name_1' : pd.Series(np.arange(3)),
     'col_name_2' : pd.Series([3.1, 3.2, 3.3]),
     }

# Create data frame
df = pd.DataFrame(d)
df

col_name_1  col_name_2
0           0         3.1
1           1         3.2
2           2         3.3

In [69]:
# Change index
df.index = ['a','b','c']
df

col_name_1  col_name_2
a           0         3.1
b           1         3.2
c           2         3.3

In [73]:
df.columns = ['C1', 'C2']
df

C1   C2
a   0  3.1
b   1  3.2
c   2  3.3